db:
  image: postgres
  volumes_from:
    - pgdata
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
pgdata:
  image: pg_data
